description: Create Java project, choose between its versions, as well as the build tool according to your preference (Gradle, Maven), make experiments, concepts validation, tests and fast algorithms creation.
name: graphene-java-standalone-stack
display-name: graphene-java-standalone-stack
picture: stack.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility: # Put a list of technologies compatible with the stack
  - java
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies 
  - java
about: docs/about.md
use-cases:
  - title: Gradle and Java 11
    content: docs/use-case-gradle-java-11.md
    stackfile: stackfiles/gradle-java-11.yaml
  - title: Maven and Java 11
    content: docs/use-case-maven-java-11.md
    stackfile: stackfiles/maven-java-11.yaml
  - title: Gradle and Java 17
    content: docs/use-case-gradle-java-17.md
    stackfile: stackfiles/gradle-java-17.yaml
  - title: Maven and Java 17
    content: docs/use-case-maven-java-17.md
    stackfile: stackfiles/maven-java-17.yaml